name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  intl: ^0.19.0
  flutter_colorpicker: ^1.1.0
  flex_color_picker: ^3.6.0
  equatable: ^2.0.0
  flutter_bloc: ^8.1.6
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  bloc: ^8.1.4 
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  

expense__repository:
    path: packages/expense_repository


flutter:
  uses-material-design: true

  assets:
    - assets/icons/entertainment.png
    - assets/icons/food.png
    - assets/icons/home.png
    - assets/icons/pet.png
    - assets/icons/shopping.png
    - assets/icons/tech.png
    - assets/icons/travel.png